venv/bin/activate: requirements.txt
	python3 -m venv venv
	./venv/bin/pip install -r requirements.txt

run: venv/bin/activate
	./venv/bin/python3 consultar_clima.py

clean:
	rm -rf venv
	find . -type f -name ‘*.pyc’ -delete

all: venv/bin/activate
